### ISSUE TITLE
Expiration time after an order was filled

### ISSUE THREAD

**Issue by MareenG** [gnosis/gp-ui#312] opened 2021-03-17 09:10 UTC
It is a bit confusing to keep the expiration time after an order was filled. 
Maybe this could be changed to execution time once the order goes through

**Comment by anxolin** [comment] 2021-03-17 10:31
Sounds like a fair proposal. The reason we show it, is because we try to show everything the user signs. So it's part of his order. However, I'm ok doing this one.

It could be
- ACTIVE + EXPIRED: Show expiration time
- CANCELED: Show cancelation time (and executed time, if it has some executions)
- FILLED: Show execution time

**Comment by anxolin** [comment] 2021-11-26 11:26
@alfetopito what do you think about this one?

**Comment by alfetopito** [comment] 2021-11-26 17:11
This is something @elena-zh raised recently.

The issue is that the backend doesn't provide us yet the `execution time` nor `cancellation time`.

One thing that we could do regarding `execution time` is to get the block time from the trade transaction.

As for the cancellation time, the backend would need to expose that if available as there is no onchain event for that.

@nlordell is cancellation time something that's easy to expose?

---

Personally given the priority, I think we could wait for backend and use the data from the api when available.

**Comment by nlordell** [comment] 2021-11-26 22:24
> is cancellation time something that's easy to expose?

Off the top of my head yes. Its part of the `orders` table and we already read it when querying order(s) to determined if its cancelled or not.

**Comment by anxolin** [comment] 2022-03-04 19:07
Closing, if we expose cancelation time we are happy to show it. Although, for now i have't seen any demand

**Closed by anxolin** 2022-03-04 19:07 UTC
Labels: ☀️ Enhancement, app:Explorer, ⬇ Low
