### ISSUE TITLE
Transaction viewer page:  Search transaction on every network

### ISSUE THREAD

**Issue by elena-zh** [gnosis/gp-ui#856] opened 2021-11-19 14:25 UTC
Related to #780 and #854

 Search transaction on every network

**Comment by alfetopito** [comment] 2021-11-19 17:10
Similar to how it's done for orderIds

**Comment by alfetopito** [comment] 2021-11-30 16:40
Sort of duplicate of/follow up to https://github.com/gnosis/gp-ui/issues/711

**Closed** 2022-01-11 14:29 UTC
Labels: app:Explorer, Protofire, ⬇ Low
