### ISSUE TITLE
Show USD price of fees and trade values in brackets

### ISSUE THREAD

**Issue by bh2smith** [gnosis/gp-ui#445] opened 2021-05-21 09:38 UTC
Like on Etherscan, it would be nice to know what the value of the amount fields are in USD.

![Screenshot 2021-05-21 at 11 37 05](https://user-images.githubusercontent.com/11778116/119116942-07aaed80-ba29-11eb-934b-cf1653f54556.png)

![Screenshot 2021-05-21 at 11 37 56](https://user-images.githubusercontent.com/11778116/119116949-0974b100-ba29-11eb-8578-ded5c5440794.png)

**Comment by alfetopito** [comment] 2021-05-21 13:25
Duplicate of https://github.com/gnosis/gp-ui/issues/171
There was even a task to do the rust part https://github.com/gnosis/gp-ui/issues/238

In other words. It's on the backlog ;)

**Closed by alfetopito** 2021-05-21 13:25 UTC
